### ISSUE TITLE
What parameters should be input for the Local Job Example of nf-ninjamap?

### ISSUE THREAD

**Issue by RChGO** [FischbachLab/nf-ninjamap#1]
I attempted to run the Local Job Example as follows:

_nextflow run -resume /share/data2/guorc/Software/ninjaMap-master.v2/nf-ninjamap-main/main.nf \
  --reads1 '/home/guorc/test3/fastq/MG867.clean_nohost.1.fq.gz' \
  --reads2 '/home/guorc/test3/fastq/MG867.clean_nohost.2.fq.gz' \
  --db  \
  --prefix db_index/ninjaIndex/tmp_20230728_074606/Sync/ninjaIndex/sc \
  -profile docker_

However, I noticed that the script does not include the '--reads1' and '--reads2' parameters. So, I tried the following command instead:

_nextflow run -resume /share/data2/guorc/Software/ninjaMap-master.v2/nf-ninjamap-main/main.nf \
  --seedfile fq.list \
  --db_path db_index/ninjaIndex/tmp_20230728_074606/Sync/ninjaIndex \
  --db_prefix sc \
  --db sc.ninjaIndex.fasta \
  --output_path map/MG867 \
  -profile docker_

Unfortunately, I still received an error warning: "When using awsbatch executor, an S3 bucket must be provided as a working directory either using the -bucket-dir or -work-dir command line option."

Do you happen to know how to resolve this issue?

Additionally, I am quite confused about the input content for "--db_path", "--db_prefix", and "--db". Could you provide more specific descriptions? In the "db_index/ninjaIndex/tmp_20230728_074606/Sync/ninjaIndex" path, there are only two files: "sc.ninjaIndex.binmap.csv" and "sc.ninjaIndex.fasta".

**Comment by xmeng** [comment]
Sorry for the confusion. Please refer to the updated README file in https://github.com/FischbachLab/nf-ninjaindex

**Comment by RChGO** [comment]
> Sorry for the confusion. Please refer to the updated README file in https://github.com/FischbachLab/nf-ninjaindex

Thank you so much for providing the new document instructions and test files. I tried the new command as follows:

_nextflow run /share/data2/guorc/Software/ninjaMap-master/nf-ninjamap-main/main-local.nf \
  --reads1 'read1.fastq.gz' \
  --reads2 'read2.fastq.gz' \
  --db HCom2_20221117 \
  --db_prefix HCom2 \
  --output_path './map' \
  -profile docker_

However, it still failed, and I received the following warning:
"When using the awsbatch executor, an S3 bucket must be provided as a working directory either using the -bucket-dir or -work-dir command line option."

Is the --output_path required to be an S3 bucket? Is there a way to run this command successfully without using awsbatch since we don't have an AWS account?

**Comment by xmeng** [comment]
The entire pipeline was built based on cloud computing utilizing ec2 and s3 from the beginning. However, you may run this pipeline in two steps. First, aligning the sample to the concatenated reference genomes. Second, running a ninjaMap docker container with a binmap file generated from the ninjaIndex pipeline, and a sorted BAM file from the first step. Below is an example to run a single sample against the HCom2 database. 

docker container run \
    -v /host/path/to/indata/:/input_data/ \
    -v /host/path/to/outdata/:/output_data/ \
    fischbachlab/nf-ninjamap \
    python /work/scripts/ninjaMap_parallel_5.py \
    -bin /input_data/db/HCom2.ninjaIndex.binmap.csv \
    -bam /input_data/bam/sample.sortedByCoord.bam \
    -outdir /output_data/summary \
    -prefix HCom2
