### ISSUE TITLE
Running ninjamap without docker 

### ISSUE THREAD

**Issue by liatbi** [FischbachLab/nf-ninjamap#3]
Hi
We would like to run ninjamap tool on HPC cluster, but we are unable to install docker.
Is it possible to run your tool without docker?
Thank you in advance.
Liat

**Comment by xmeng** [comment]
Hi Liat,

Thanks for your inquiry. I am sorry that the ninjamap tool is designed to run on aws only. If you'd like to port the software to hpc, you get to convert docker to singularity and modify the scripts according to your hpc environments on your own. 

Best,
xmeng
